server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  
      routes:
        - id: Micro-cursos
          uri: lb://COURSES-MS
          predicates:
            - Path=/cursos/**
        - id: Micro-Estudiantes
          uri: lb://STUDENTS-MS
          predicates:
            - Path=/estudiantes/**

  config:
    import: "optional:configserver:"  

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always  
  health:
    db:
      enabled: true  
    diskspace:
      enabled: true  
    ping:
      enabled: true  
 














