server:
  port: 8082

spring:
  application:
    name: students-ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
        provider:
          google:
            issuer-uri: https://accounts.google.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


